version: '3.8'

services:
  backend:
    build: .
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python backend/app.py